### ISSUE TITLE
After successful build and upload, device restarts every 5-10 seconds. Blank screen. No sound.

### ISSUE THREAD

**Issue by sinitsinmike** [kikiisdead/minichord#5]
After compiling and uploading the code to teensy, I get the message in the terminal: CAP1188 found!, SSD1306 allocation success! And that's it, no further messages. Display is blank, and device restarts every 5-10 seconds. Your inpit would be greatly appreciated! Thank you!

**Comment by kikiisdead** [comment]
I pushed some changes into the repository. lemme know if it persists when you build it now.

**Comment by sinitsinmike** [comment]
Thank you! Definitely an improvement. There's text now on the display.
But auto-restart is still happening every 10 seconds.
Rotating the encoder and or pressing buttons nor strumming doesn't make any difference. No sound. Rotating the encoder doesn't change anything on the screen.

![Image](https://github.com/user-attachments/assets/6925d27e-89db-49f4-9dd6-c7ac45cbe694)

![Image](https://github.com/user-attachments/assets/600847c0-b5b4-4cad-a0d1-9bdbf3c7edfc)

**Comment by sinitsinmike** [comment]
![Image](https://github.com/user-attachments/assets/1b89be0b-d3ad-4f2c-bc57-0073f418c2be)

**Comment by kikiisdead** [comment]
I just want to make sure that the audio head is installed correctly. Do you mind sending a picture of the bottom side of the board?

**Comment by sinitsinmike** [comment]
I am using an alternative board. It is PCM5102. It is connected correctly. I've executed a simple code with a sine wave to make sure there's oudio out. I've ordered the audio shield you've used. It is in the mail. Will get it in a few weeks.

Yahoo Почта: Поиск, организация, успех 
 
  пт, 21 мар. 2025 в 19:20 ***@***.***> написал(-а):    
I just want to make sure that the audio head is installed correctly. Do you mind sending a picture of the bottom side of the board?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
kikiisdead left a comment (kikiisdead/minichord#5)
I just want to make sure that the audio head is installed correctly. Do you mind sending a picture of the bottom side of the board?

**Comment by sinitsinmike** [comment]
I am using an alternative board. It is PCM5102. It is connected correctly. I've executed a simple code with a sine wave to make sure there's oudio out. I've ordered the audio shield you've used. It is in the mail. Will get it in a few weeks.
Is there a check in the code that requires you specific board to be present and connected?
Would it explain why rotating the encoder doesn't make a difference?

**Comment by sinitsinmike** [comment]
Also tried various displays with 0x3D and 0x3C addresses, adjusting the address in the code. Previously that didn't work, with your last changes both displays display text. But, rotating the encoder doesn't change any parameters. the text on display remains unchanged.

**Comment by kikiisdead** [comment]
From what I can tell, the issue lies either in the EEPROM read or in the audio connection side of the code. From your photos, it looks like the program is stalling in the setup phase after the display and after the capacitive touch sensor. It never reaches the end of the setup phase because "I'm working" is not being printed to the terminal. This means that either the EEPROM.read is failing or the audio shield is not starting correctly.

The reason why the text on screen isn't changing is because we never reach the loop part of the program where that logic is handled. Everything is stalling in the set-up portion. 

I want to make sure that it is not a hardware issue that's why I'm asking for photos.

**Comment by sinitsinmike** [comment]
![Image](https://github.com/user-attachments/assets/f3593548-5b6c-4743-bbd3-61546b5dd723)
![Image](https://github.com/user-attachments/assets/0cce463a-d33d-47cb-97bd-f7aa4ac51e7d)
Here are a few photos of the wiring.

**Comment by sinitsinmike** [comment]
![Image](https://github.com/user-attachments/assets/78986be3-7f41-47cd-8c67-3c6eca00f645)

![Image](https://github.com/user-attachments/assets/66494c27-40c5-4a6c-8db6-5841835faa92)

**Comment by kikiisdead** [comment]
That's the wrong audio shield. I should have been more specific in the readme. You need the Teensy audio adaptor for Teensy 4.x. https://www.adafruit.com/product/4384

The project is built using the teensy audio library which only works with the teensy audio adaptor. The mouser project page has all the required materials in one spot so you can buy it very easily.

**Comment by sinitsinmike** [comment]
Oh, no, you were quite specific, I saw the BOM and am aware that I'm using the wrong one.
I thought that because both are i2s this one should work as well. My thoughts were that if the oudio goes to i2s, it doesn't matter which dac chip is revieving the data. And the one I'm using is a fraction of the cost.
Yes, I understand. That specific shield is in the mail.
For now I'll try to make it work with pcm5102, even though my qualification isn't high enough to completely rewrite the shield related code.
As soon as I recieve the shield you've specified, I'll install it.
